version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: kill_container.sh
      timeout: 20
      runas: ubuntu
  ApplicationStart:
    - location: start_container.sh
      timeout: 10
      runas: ubuntu